package order

const (
	//order status
	ORDER_CREATED    string = "ORDER_CREATED"
	ORDER_PROCESSING string = "ORDER_PROCESSING"
	ORDER_REFUNDING  string = "ORDER_REFUNDING"
	ORDER_REFUNDED   string = "ORDER_REFUNDED"
	ORDER_DELIVERED  string = "ORDER_DELIVERED"
	ORDER_FAILED     string = "ORDER_FAILED"
	ORDER_DONE       string = "ORDER_DONE"
	// order substatus
	ORDER_PAYMENT_PAID               string = "ORDER_PAYMENT_PAID"
	ORDER_PAYMENT_FAILED             string = "ORDER_PAYMENT_FAILED"
	ORDER_KTCHENT_PREPARATION_FAILED string = "ORDER_KTCHENT_PREPARATION_FAILED"
)
